"""The LLM boundary.

Two rules shape this module.

**Everything upstream talks to `LLMClient`, never to a provider.** A fake client can then
fail on demand, so the degradation path — which is the part that actually matters clinically —
is testable without a network, an API key, or a bill.

**The model's answer is schema-constrained, not parsed hopefully.** Both providers are given
the pydantic model as the output contract, so nothing downstream ever sees unvalidated text.
They differ in how far that goes, and the difference is worth knowing: Anthropic's SDK returns
an already-parsed object, while Gemini returns the JSON as a *string* that this module has to
decode. So malformed JSON is a real failure mode on the Gemini path and an impossible one on
the Anthropic path. Neither is a "parse and hope" — the schema is enforced either way — but
only one of them can fail at the decode step.
"""

from __future__ import annotations

import json
import logging
from typing import Any, Protocol, TypeVar

import anthropic
import httpx
from pydantic import BaseModel, Field, ValidationError, field_validator

from app.core.config import Settings

logger = logging.getLogger(__name__)

OutputT = TypeVar("OutputT", bound=BaseModel)

SUGGESTED_QUESTION_COUNT = 3


class LLMError(Exception):
    """The model could not be reached or did not answer. Worth retrying."""


class LLMRefusal(Exception):
    """The model declined to answer.

    Terminal rather than retryable: the same request will be declined again. It is recorded
    on the summary so a doctor can see the brief is unavailable rather than merely late.
    """


# --------------------------------------------------------------------------- output schemas


class PreVisitSummary(BaseModel):
    """The brief a doctor sees before the consultation."""

    urgency: str = Field(description="One of: low, medium, high.")
    chief_complaint: str = Field(description="The main problem, in one short line.")
    suggested_questions: list[str] = Field(
        description=f"Exactly {SUGGESTED_QUESTION_COUNT} questions worth asking the patient."
    )

    @field_validator("urgency")
    @classmethod
    def _normalise_urgency(cls, value: str) -> str:
        # The prompt asks for "Low / Medium / High"; the database stores lower case.
        normalised = value.strip().lower()
        if normalised not in {"low", "medium", "high"}:
            raise ValueError(f"urgency must be low, medium or high (got {value!r})")
        return normalised


class PostVisitSummary(BaseModel):
    """The plain-language write-up a patient receives after the consultation."""

    summary: str = Field(description="What happened at the visit, in everyday language.")
    medication_schedule: list[str] = Field(
        description="One line per medicine: what to take, how much, and when."
    )
    follow_up_steps: list[str] = Field(description="What the patient should do next.")


# --------------------------------------------------------------------------- the boundary


class LLMClient(Protocol):
    """What the summary worker needs from a language model."""

    async def generate(
        self,
        *,
        system: str,
        user: str,
        output_model: type[OutputT],
        max_tokens: int,
    ) -> OutputT:
        """Return a validated instance of `output_model`, or raise `LLMError`/`LLMRefusal`."""
        ...


class StubLLMClient:
    """A deterministic stand-in used in development and tests.

    Returns something structurally valid and obviously synthetic. It never pretends to be
    clinical judgement — the point is to exercise the surrounding machinery, and a stub that
    looked like a real triage decision would be dangerous if it ever reached a screen.
    """

    async def generate(
        self,
        *,
        system: str,
        user: str,
        output_model: type[OutputT],
        max_tokens: int,
    ) -> OutputT:
        if output_model is PreVisitSummary:
            return output_model.model_validate(
                {
                    "urgency": "medium",
                    "chief_complaint": "[stub] Summary not generated by a language model.",
                    "suggested_questions": [
                        "[stub] How long have the symptoms lasted?",
                        "[stub] Has anything made them better or worse?",
                        "[stub] Any other symptoms alongside these?",
                    ],
                }
            )
        if output_model is PostVisitSummary:
            return output_model.model_validate(
                {
                    "summary": "[stub] Summary not generated by a language model.",
                    "medication_schedule": ["[stub] Follow the schedule your doctor gave you."],
                    "follow_up_steps": ["[stub] Contact the clinic if symptoms worsen."],
                }
            )
        raise LLMError(f"the stub client has no canned answer for {output_model.__name__}")


class AnthropicLLMClient:
    """Calls the Anthropic API through its official SDK.

    Uses structured outputs: the response is validated against `output_model` by the SDK, so
    a malformed answer is not a failure mode the caller has to handle.
    """

    def __init__(
        self,
        *,
        api_key: str,
        model: str,
        timeout_seconds: float,
        client: anthropic.AsyncAnthropic | None = None,
    ) -> None:
        self._model = model
        # Injectable so tests can assert on the request without reaching the network.
        self._client = client or anthropic.AsyncAnthropic(api_key=api_key, timeout=timeout_seconds)

    async def generate(
        self,
        *,
        system: str,
        user: str,
        output_model: type[OutputT],
        max_tokens: int,
    ) -> OutputT:
        try:
            response = await self._client.messages.parse(
                model=self._model,
                max_tokens=max_tokens,
                system=system,
                messages=[{"role": "user", "content": user}],
                output_format=output_model,
            )
        except anthropic.APITimeoutError as error:
            raise LLMError(f"the model timed out: {error}") from error
        except anthropic.RateLimitError as error:
            raise LLMError(f"rate limited by the model provider: {error}") from error
        except anthropic.APIConnectionError as error:
            raise LLMError(f"could not reach the model provider: {error}") from error
        except anthropic.APIStatusError as error:
            # 4xx is a bug in our request and will fail identically on retry, but the retry
            # budget is small and a summary failing costs nothing clinically, so both are
            # surfaced the same way rather than adding a second failure taxonomy.
            raise LLMError(
                f"model provider returned {error.status_code}: {error.message}"
            ) from error

        # A safety decline arrives as a normal 200 response, so it has to be checked for
        # explicitly. Clinical text makes this a realistic outcome, not a theoretical one.
        if response.stop_reason == "refusal":
            raise LLMRefusal("the model declined to answer this request")

        parsed = response.parsed_output
        if parsed is None:
            raise LLMError("the model returned no structured output")
        return parsed


class GeminiLLMClient:
    """Calls the Gemini Interactions API over plain HTTPS.

    No `google-genai` SDK: the request is one POST and the response needs one walk down two
    typed arrays, which is less code than pinning and auditing another dependency — and the
    same reasoning that kept the Google Calendar integration on `httpx`.

    The response shape is the part worth reading, because it is not obvious and getting it
    wrong fails on every call. `steps` is a list of *typed* steps, and this model reasons by
    default, so the first entry is a `thought` and the answer is in a later `model_output`
    step. Its `content` is itself a list of typed parts. Indexing `steps[0]` or `content[0]`
    happens to work only when reasoning is off.
    """

    ENDPOINT = "https://generativelanguage.googleapis.com/v1beta/interactions"

    def __init__(
        self,
        *,
        api_key: str,
        model: str,
        timeout_seconds: float,
        transport: httpx.AsyncBaseTransport | None = None,
    ) -> None:
        self._api_key = api_key
        self._model = model
        self._timeout = timeout_seconds
        # Injectable so the exact request and every failure branch can be asserted against a
        # mock transport, with no key and no network.
        self._transport = transport

    async def generate(
        self,
        *,
        system: str,
        user: str,
        output_model: type[OutputT],
        max_tokens: int,
    ) -> OutputT:
        payload: dict[str, Any] = {
            "model": self._model,
            "input": user,
            # A real system role rather than text prepended to the prompt: the instruction
            # that patient symptoms are data and never commands is the prompt-injection
            # defence, and it should not sit in the same channel as the untrusted text.
            "system_instruction": system,
            "generation_config": {"max_output_tokens": max_tokens},
            "response_format": {
                "type": "text",
                "mime_type": "application/json",
                "schema": _json_schema_for(output_model),
            },
        }

        try:
            async with httpx.AsyncClient(
                timeout=self._timeout, transport=self._transport
            ) as client:
                response = await client.post(
                    self.ENDPOINT,
                    headers={"x-goog-api-key": self._api_key, "Content-Type": "application/json"},
                    json=payload,
                )
        except httpx.HTTPError as error:
            raise LLMError(f"could not reach the model provider: {error}") from error

        if response.status_code >= 400:
            # The body can echo the prompt, which for a pre-visit summary is a patient's
            # symptoms. Only the status and Google's short reason are surfaced.
            raise LLMError(
                f"model provider returned {response.status_code}: {_gemini_error(response)}"
            )

        try:
            body: dict[str, Any] = response.json()
        except ValueError as error:
            raise LLMError("the model provider returned a non-JSON response") from error

        _check_status(body)
        return _parse_output(body, output_model)


def _json_schema_for(output_model: type[BaseModel]) -> dict[str, Any]:
    """The output contract, as the schema Gemini enforces.

    `title` keys are stripped because pydantic emits one per field and they are noise in a
    schema whose only job is to constrain shape.
    """
    stripped: dict[str, Any] = _without_titles(output_model.model_json_schema())
    return stripped


def _without_titles(node: Any) -> Any:
    if isinstance(node, dict):
        return {key: _without_titles(value) for key, value in node.items() if key != "title"}
    if isinstance(node, list):
        return [_without_titles(item) for item in node]
    return node


# Terminal states: the model was stopped rather than delayed, so a retry reaches the same
# place. Everything else unexpected is treated as retryable, because guessing that an
# unfamiliar state is permanent risks discarding a summary that would have succeeded.
_REFUSAL_STATUSES = frozenset({"failed", "cancelled"})
_SAFETY_MARKERS = ("safety", "blocked", "prohibited", "policy")


def _check_status(body: dict[str, Any]) -> None:
    status = body.get("status")
    if status == "completed":
        return

    reason = "; ".join(
        str(error.get("message", "")) for error in body.get("errors", []) if isinstance(error, dict)
    )

    if status in _REFUSAL_STATUSES and any(marker in reason.lower() for marker in _SAFETY_MARKERS):
        # Declining clinical text is a realistic outcome, and it is a decision about *this*
        # request — retrying only spends quota to be refused again.
        raise LLMRefusal(f"the model declined to answer this request: {reason}")

    if status == "budget_exceeded":
        raise LLMError("the model ran out of output tokens before finishing")

    raise LLMError(f"the model did not complete (status: {status or 'unknown'}) {reason}".strip())


def _parse_output(body: dict[str, Any], output_model: type[OutputT]) -> OutputT:
    """Walk `steps` -> the `model_output` step -> its text parts -> JSON -> the contract."""
    steps = body.get("steps")
    if not isinstance(steps, list):
        raise LLMError("the model returned no steps")

    text = ""
    for step in steps:
        # Skipped rather than indexed: a `thought` step comes first whenever the model
        # reasons, which for this one is the default.
        if not isinstance(step, dict) or step.get("type") != "model_output":
            continue
        parts = step.get("content")
        if isinstance(parts, list):
            text += "".join(
                str(part.get("text", ""))
                for part in parts
                if isinstance(part, dict) and part.get("type") == "text"
            )

    if not text.strip():
        raise LLMError("the model returned no output text")

    try:
        parsed = json.loads(text)
    except json.JSONDecodeError as error:
        # Reachable in a way the Anthropic path is not: this provider hands back JSON as a
        # string, so decoding it is a step that can genuinely fail.
        raise LLMError(f"the model returned text that is not valid JSON: {error}") from error

    try:
        return output_model.model_validate(parsed)
    except ValidationError as error:
        raise LLMError(f"the model's answer did not match the required shape: {error}") from error


def _gemini_error(response: httpx.Response) -> str:
    """Google's short message, never the whole body."""
    try:
        payload = response.json()
    except ValueError:
        return "unparseable error response"
    if isinstance(payload, dict):
        error = payload.get("error")
        if isinstance(error, dict):
            message = error.get("message")
            if isinstance(message, str):
                return message[:200]
        errors = payload.get("errors")
        if isinstance(errors, list) and errors and isinstance(errors[0], dict):
            return str(errors[0].get("message", ""))[:200]
    return "unknown error"


def build_llm_client(settings: Settings) -> LLMClient:
    """Choose a client from configuration.

    A real provider with no API key fails loudly rather than falling back to the stub:
    silently serving canned text as if it were a clinical summary is the worst outcome
    available here.
    """
    if settings.llm_provider == "stub":
        return StubLLMClient()

    if settings.llm_api_key is None:
        raise ValueError(
            f"LLM_PROVIDER is {settings.llm_provider!r} but LLM_API_KEY is not set. "
            "Set the key, or use LLM_PROVIDER=stub for local development."
        )
    key = settings.llm_api_key.get_secret_value()

    if settings.llm_provider == "gemini":
        return GeminiLLMClient(
            api_key=key,
            model=settings.llm_model,
            timeout_seconds=settings.llm_timeout_seconds,
        )
    return AnthropicLLMClient(
        api_key=key,
        model=settings.llm_model,
        timeout_seconds=settings.llm_timeout_seconds,
    )
