"""The LLM boundary.

Two rules shape this module.

**Everything upstream talks to `LLMClient`, never to a provider.** A fake client can then
fail on demand, so the degradation path — which is the part that actually matters clinically —
is testable without a network, an API key, or a bill.

**The model's answer is schema-constrained, not parsed hopefully.** Requests go through the
SDK's structured-output support with a pydantic model as the contract, so the response is
validated before it reaches any calling code. There is no "parse the JSON and hope" step and
no regex salvage of half-formed output.
"""

from __future__ import annotations

import logging
from typing import Protocol, TypeVar

import anthropic
from pydantic import BaseModel, Field, field_validator

from app.core.config import Settings

logger = logging.getLogger(__name__)

OutputT = TypeVar("OutputT", bound=BaseModel)

SUGGESTED_QUESTION_COUNT = 3


class LLMError(Exception):
    """The model could not be reached or did not answer. Worth retrying."""


class LLMRefusal(Exception):
    """The model declined to answer.

    Terminal rather than retryable: the same request will be declined again. It is recorded
    on the summary so a doctor can see the brief is unavailable rather than merely late.
    """


# --------------------------------------------------------------------------- output schemas


class PreVisitSummary(BaseModel):
    """The brief a doctor sees before the consultation."""

    urgency: str = Field(description="One of: low, medium, high.")
    chief_complaint: str = Field(description="The main problem, in one short line.")
    suggested_questions: list[str] = Field(
        description=f"Exactly {SUGGESTED_QUESTION_COUNT} questions worth asking the patient."
    )

    @field_validator("urgency")
    @classmethod
    def _normalise_urgency(cls, value: str) -> str:
        # The prompt asks for "Low / Medium / High"; the database stores lower case.
        normalised = value.strip().lower()
        if normalised not in {"low", "medium", "high"}:
            raise ValueError(f"urgency must be low, medium or high (got {value!r})")
        return normalised


class PostVisitSummary(BaseModel):
    """The plain-language write-up a patient receives after the consultation."""

    summary: str = Field(description="What happened at the visit, in everyday language.")
    medication_schedule: list[str] = Field(
        description="One line per medicine: what to take, how much, and when."
    )
    follow_up_steps: list[str] = Field(description="What the patient should do next.")


# --------------------------------------------------------------------------- the boundary


class LLMClient(Protocol):
    """What the summary worker needs from a language model."""

    async def generate(
        self,
        *,
        system: str,
        user: str,
        output_model: type[OutputT],
        max_tokens: int,
    ) -> OutputT:
        """Return a validated instance of `output_model`, or raise `LLMError`/`LLMRefusal`."""
        ...


class StubLLMClient:
    """A deterministic stand-in used in development and tests.

    Returns something structurally valid and obviously synthetic. It never pretends to be
    clinical judgement — the point is to exercise the surrounding machinery, and a stub that
    looked like a real triage decision would be dangerous if it ever reached a screen.
    """

    async def generate(
        self,
        *,
        system: str,
        user: str,
        output_model: type[OutputT],
        max_tokens: int,
    ) -> OutputT:
        if output_model is PreVisitSummary:
            return output_model.model_validate(
                {
                    "urgency": "medium",
                    "chief_complaint": "[stub] Summary not generated by a language model.",
                    "suggested_questions": [
                        "[stub] How long have the symptoms lasted?",
                        "[stub] Has anything made them better or worse?",
                        "[stub] Any other symptoms alongside these?",
                    ],
                }
            )
        if output_model is PostVisitSummary:
            return output_model.model_validate(
                {
                    "summary": "[stub] Summary not generated by a language model.",
                    "medication_schedule": ["[stub] Follow the schedule your doctor gave you."],
                    "follow_up_steps": ["[stub] Contact the clinic if symptoms worsen."],
                }
            )
        raise LLMError(f"the stub client has no canned answer for {output_model.__name__}")


class AnthropicLLMClient:
    """Calls Claude through the official SDK.

    Uses structured outputs: the response is validated against `output_model` by the SDK, so
    a malformed answer is not a failure mode the caller has to handle.
    """

    def __init__(
        self,
        *,
        api_key: str,
        model: str,
        timeout_seconds: float,
        client: anthropic.AsyncAnthropic | None = None,
    ) -> None:
        self._model = model
        # Injectable so tests can assert on the request without reaching the network.
        self._client = client or anthropic.AsyncAnthropic(api_key=api_key, timeout=timeout_seconds)

    async def generate(
        self,
        *,
        system: str,
        user: str,
        output_model: type[OutputT],
        max_tokens: int,
    ) -> OutputT:
        try:
            response = await self._client.messages.parse(
                model=self._model,
                max_tokens=max_tokens,
                system=system,
                messages=[{"role": "user", "content": user}],
                output_format=output_model,
            )
        except anthropic.APITimeoutError as error:
            raise LLMError(f"the model timed out: {error}") from error
        except anthropic.RateLimitError as error:
            raise LLMError(f"rate limited by the model provider: {error}") from error
        except anthropic.APIConnectionError as error:
            raise LLMError(f"could not reach the model provider: {error}") from error
        except anthropic.APIStatusError as error:
            # 4xx is a bug in our request and will fail identically on retry, but the retry
            # budget is small and a summary failing costs nothing clinically, so both are
            # surfaced the same way rather than adding a second failure taxonomy.
            raise LLMError(
                f"model provider returned {error.status_code}: {error.message}"
            ) from error

        # A safety decline arrives as a normal 200 response, so it has to be checked for
        # explicitly. Clinical text makes this a realistic outcome, not a theoretical one.
        if response.stop_reason == "refusal":
            raise LLMRefusal("the model declined to answer this request")

        parsed = response.parsed_output
        if parsed is None:
            raise LLMError("the model returned no structured output")
        return parsed


def build_llm_client(settings: Settings) -> LLMClient:
    """Choose a client from configuration.

    An `anthropic` provider with no API key fails loudly rather than falling back to the stub:
    silently serving canned text as if it were a clinical summary is the worst outcome
    available here.
    """
    if settings.llm_provider == "anthropic":
        if settings.llm_api_key is None:
            raise ValueError(
                "LLM_PROVIDER is 'anthropic' but LLM_API_KEY is not set. "
                "Set the key, or use LLM_PROVIDER=stub for local development."
            )
        return AnthropicLLMClient(
            api_key=settings.llm_api_key.get_secret_value(),
            model=settings.llm_model,
            timeout_seconds=settings.llm_timeout_seconds,
        )
    return StubLLMClient()
