"""add calendar connections and sync jobs

Phase 7. Two tables: the per-user Google authorisation (with the refresh token stored
encrypted, never in plaintext) and the reconciler that holds what each participant's
calendar should show for each appointment.

The unique constraint on (appointment_id, user_id) is load-bearing rather than tidy: the
sync table stores desired state, so exactly one row per calendar per appointment is what
makes a cancellation impossible to apply before the booking it cancels.

Revision ID: 6db78daa0931
Revises: 9ccb250f621f
Create Date: 2026-08-20 23:53:36.226257
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6db78daa0931"
down_revision: str | None = "9ccb250f621f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar_connections",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("google_account_email", sa.String(length=320), nullable=False),
        sa.Column("calendar_id", sa.String(length=255), server_default="primary", nullable=False),
        sa.Column("encrypted_refresh_token", sa.Text(), nullable=False),
        sa.Column("granted_scope", sa.Text(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_calendar_connections_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_connections")),
        sa.UniqueConstraint("user_id", name=op.f("uq_calendar_connections_user_id")),
    )
    op.create_table(
        "calendar_sync_jobs",
        sa.Column("appointment_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.Enum("sync", "delete", name="calendar_sync_action"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "synced", "skipped", "failed", name="calendar_sync_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("google_event_id", sa.String(length=1024), nullable=False),
        sa.Column("calendar_id", sa.String(length=255), server_default="primary", nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_calendar_sync_jobs_calendar_attempts_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
            name=op.f("fk_calendar_sync_jobs_appointment_id_appointments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_calendar_sync_jobs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_sync_jobs")),
        sa.UniqueConstraint("appointment_id", "user_id", name="uq_calendar_sync_appointment_user"),
    )
    op.create_index(
        "ix_calendar_sync_jobs_due",
        "calendar_sync_jobs",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_calendar_sync_jobs_due",
        table_name="calendar_sync_jobs",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("calendar_sync_jobs")
    op.drop_table("calendar_connections")
    # ### end Alembic commands ###

    # Same omission as the initial migration: `drop_table` leaves the native enum types
    # behind, so a downgrade followed by an upgrade would fail with
    # `type "calendar_sync_action" already exists`. Round-trip verified.
    for enum_name in ("calendar_sync_status", "calendar_sync_action"):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
