"""add retry schedule to ai summaries

Revision ID: 9ccb250f621f
Revises: df66272d6310
Create Date: 2026-08-20 22:57:54.224104
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9ccb250f621f"
down_revision: str | None = "df66272d6310"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_summaries", sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_summaries", "next_attempt_at")
    # ### end Alembic commands ###
