"""create core schema

Revision ID: df66272d6310
Revises:
Create Date: 2026-08-20 19:54:07.652273
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "df66272d6310"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.Enum("patient", "doctor", "admin", name="user_role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "doctor_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("specialisation", sa.String(length=120), nullable=False),
        sa.Column("slot_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slot_duration_minutes > 0 AND slot_duration_minutes <= 240",
            name=op.f("ck_doctor_profiles_slot_duration_within_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_doctor_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_doctor_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_doctor_profiles_user_id")),
    )
    op.create_index(
        op.f("ix_doctor_profiles_specialisation"),
        "doctor_profiles",
        ["specialisation"],
        unique=False,
    )
    op.create_table(
        "appointments",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("doctor_profile_id", sa.UUID(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "held",
                "confirmed",
                "completed",
                "cancelled_by_patient",
                "cancelled_by_clinic",
                name="appointment_status",
            ),
            server_default="held",
            nullable=False,
        ),
        sa.Column("hold_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=255), nullable=True),
        sa.Column("patient_calendar_event_id", sa.String(length=255), nullable=True),
        sa.Column("doctor_calendar_event_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'held' OR hold_expires_at IS NOT NULL",
            name=op.f("ck_appointments_held_appointment_has_expiry"),
        ),
        sa.CheckConstraint(
            "ends_at > starts_at", name=op.f("ck_appointments_appointment_ends_after_it_starts")
        ),
        sa.ForeignKeyConstraint(
            ["doctor_profile_id"],
            ["doctor_profiles.id"],
            name=op.f("fk_appointments_doctor_profile_id_doctor_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["users.id"],
            name=op.f("fk_appointments_patient_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointments")),
    )
    op.create_index(
        "ix_appointments_doctor_starts_at",
        "appointments",
        ["doctor_profile_id", "starts_at"],
        unique=False,
    )
    op.create_index(
        "ix_appointments_patient_starts_at",
        "appointments",
        ["patient_id", "starts_at"],
        unique=False,
    )
    op.create_index(
        "uq_appointments_doctor_occupied_slot",
        "appointments",
        ["doctor_profile_id", "starts_at"],
        unique=True,
        postgresql_where=sa.text("status IN ('held', 'confirmed', 'completed')"),
    )
    op.create_table(
        "doctor_leave_days",
        sa.Column("doctor_profile_id", sa.UUID(), nullable=False),
        sa.Column("leave_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["doctor_profile_id"],
            ["doctor_profiles.id"],
            name=op.f("fk_doctor_leave_days_doctor_profile_id_doctor_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_doctor_leave_days")),
        sa.UniqueConstraint("doctor_profile_id", "leave_date", name="uq_doctor_leave_days_date"),
    )
    op.create_index(
        op.f("ix_doctor_leave_days_doctor_profile_id"),
        "doctor_leave_days",
        ["doctor_profile_id"],
        unique=False,
    )
    op.create_table(
        "doctor_working_hours",
        sa.Column("doctor_profile_id", sa.UUID(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_time > start_time",
            name=op.f("ck_doctor_working_hours_window_ends_after_it_starts"),
        ),
        sa.CheckConstraint(
            "weekday BETWEEN 0 AND 6", name=op.f("ck_doctor_working_hours_weekday_within_week")
        ),
        sa.ForeignKeyConstraint(
            ["doctor_profile_id"],
            ["doctor_profiles.id"],
            name=op.f("fk_doctor_working_hours_doctor_profile_id_doctor_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_doctor_working_hours")),
        sa.UniqueConstraint(
            "doctor_profile_id", "weekday", "start_time", name="uq_doctor_working_hours_slot_start"
        ),
    )
    op.create_index(
        op.f("ix_doctor_working_hours_doctor_profile_id"),
        "doctor_working_hours",
        ["doctor_profile_id"],
        unique=False,
    )
    op.create_table(
        "ai_summaries",
        sa.Column("appointment_id", sa.UUID(), nullable=False),
        sa.Column(
            "summary_type", sa.Enum("pre_visit", "post_visit", name="summary_type"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "ready", "failed", name="summary_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("urgency", sa.Enum("low", "medium", "high", name="urgency_level"), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'ready' OR content IS NOT NULL",
            name=op.f("ck_ai_summaries_ready_summary_has_content"),
        ),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_ai_summaries_ai_summary_attempts_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
            name=op.f("fk_ai_summaries_appointment_id_appointments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_summaries")),
        sa.UniqueConstraint("appointment_id", "summary_type", name="uq_ai_summaries_per_type"),
    )
    op.create_index(
        op.f("ix_ai_summaries_appointment_id"), "ai_summaries", ["appointment_id"], unique=False
    )
    op.create_table(
        "notification_jobs",
        sa.Column(
            "notification_type",
            sa.Enum(
                "booking_confirmation",
                "appointment_reminder",
                "cancellation",
                "leave_conflict",
                "medication_reminder",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "sent", "failed", name="notification_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("recipient_email", sa.String(length=320), nullable=False),
        sa.Column("recipient_user_id", sa.UUID(), nullable=True),
        sa.Column("appointment_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'sent' OR sent_at IS NOT NULL",
            name=op.f("ck_notification_jobs_sent_notification_has_timestamp"),
        ),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_notification_jobs_notification_attempts_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
            name=op.f("fk_notification_jobs_appointment_id_appointments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"],
            ["users.id"],
            name=op.f("fk_notification_jobs_recipient_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_jobs")),
    )
    op.create_index(
        op.f("ix_notification_jobs_appointment_id"),
        "notification_jobs",
        ["appointment_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_jobs_due",
        "notification_jobs",
        ["scheduled_for"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "prescriptions",
        sa.Column("appointment_id", sa.UUID(), nullable=False),
        sa.Column("clinical_notes", sa.Text(), nullable=False),
        sa.Column("follow_up_date", sa.Date(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
            name=op.f("fk_prescriptions_appointment_id_appointments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prescriptions")),
        sa.UniqueConstraint("appointment_id", name=op.f("uq_prescriptions_appointment_id")),
    )
    op.create_table(
        "symptom_reports",
        sa.Column("appointment_id", sa.UUID(), nullable=False),
        sa.Column("symptoms", sa.Text(), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=True),
        sa.Column("additional_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_days IS NULL OR duration_days >= 0",
            name=op.f("ck_symptom_reports_symptom_duration_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
            name=op.f("fk_symptom_reports_appointment_id_appointments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_symptom_reports")),
        sa.UniqueConstraint("appointment_id", name=op.f("uq_symptom_reports_appointment_id")),
    )
    op.create_table(
        "prescription_medications",
        sa.Column("prescription_id", sa.UUID(), nullable=False),
        sa.Column("drug_name", sa.String(length=200), nullable=False),
        sa.Column("dosage", sa.String(length=100), nullable=False),
        sa.Column("times_per_day", sa.Integer(), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("instructions", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_days > 0 AND duration_days <= 365",
            name=op.f("ck_prescription_medications_medication_duration_within_bounds"),
        ),
        sa.CheckConstraint(
            "times_per_day > 0 AND times_per_day <= 12",
            name=op.f("ck_prescription_medications_medication_frequency_within_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["prescription_id"],
            ["prescriptions.id"],
            name=op.f("fk_prescription_medications_prescription_id_prescriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prescription_medications")),
    )
    op.create_index(
        op.f("ix_prescription_medications_prescription_id"),
        "prescription_medications",
        ["prescription_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_prescription_medications_prescription_id"), table_name="prescription_medications"
    )
    op.drop_table("prescription_medications")
    op.drop_table("symptom_reports")
    op.drop_table("prescriptions")
    op.drop_index(
        "ix_notification_jobs_due",
        table_name="notification_jobs",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("ix_notification_jobs_appointment_id"), table_name="notification_jobs")
    op.drop_table("notification_jobs")
    op.drop_index(op.f("ix_ai_summaries_appointment_id"), table_name="ai_summaries")
    op.drop_table("ai_summaries")
    op.drop_index(
        op.f("ix_doctor_working_hours_doctor_profile_id"), table_name="doctor_working_hours"
    )
    op.drop_table("doctor_working_hours")
    op.drop_index(op.f("ix_doctor_leave_days_doctor_profile_id"), table_name="doctor_leave_days")
    op.drop_table("doctor_leave_days")
    op.drop_index(
        "uq_appointments_doctor_occupied_slot",
        table_name="appointments",
        postgresql_where=sa.text("status IN ('held', 'confirmed', 'completed')"),
    )
    op.drop_index("ix_appointments_patient_starts_at", table_name="appointments")
    op.drop_index("ix_appointments_doctor_starts_at", table_name="appointments")
    op.drop_table("appointments")
    op.drop_index(op.f("ix_doctor_profiles_specialisation"), table_name="doctor_profiles")
    op.drop_table("doctor_profiles")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###

    # Not generated by autogenerate: `drop_table` leaves behind the native enum types that
    # SQLAlchemy created alongside the tables. Without this, a downgrade followed by an
    # upgrade fails with `type "user_role" already exists`. Verified by round-tripping
    # upgrade -> downgrade -> upgrade.
    for enum_name in (
        "notification_status",
        "notification_type",
        "summary_status",
        "summary_type",
        "urgency_level",
        "appointment_status",
        "user_role",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
